// Mocks generated by Mockito 5.4.0 from annotations
// in dhali_wallet/test/dhali_wallet_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dhali_wallet/wallet_types.dart' as _i3;
import 'package:dhali_wallet/xrpl_wallet.dart' as _i5;
import 'package:dhali_wallet/xumm_wallet.dart' as _i8;
import 'package:flutter/material.dart' as _i2;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:xrpl/xrpl.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentChannelDescriptor_1 extends _i1.SmartFake
    implements _i3.PaymentChannelDescriptor {
  _FakePaymentChannelDescriptor_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_2 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [XRPLWallet].
///
/// See the documentation for Mockito's code generation for more information.
class MockXRPLWallet extends _i1.Mock implements _i5.XRPLWallet {
  MockXRPLWallet() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set mnemonic(String? _mnemonic) => super.noSuchMethod(
        Invocation.setter(
          #mnemonic,
          _mnemonic,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get address => (super.noSuchMethod(
        Invocation.getter(#address),
        returnValue: '',
      ) as String);
  @override
  _i2.ValueNotifier<String?> get balance => (super.noSuchMethod(
        Invocation.getter(#balance),
        returnValue: _FakeValueNotifier_0<String?>(
          this,
          Invocation.getter(#balance),
        ),
      ) as _i2.ValueNotifier<String?>);
  @override
  String publicKey() => (super.noSuchMethod(
        Invocation.method(
          #publicKey,
          [],
        ),
        returnValue: '',
      ) as String);
  @override
  _i6.Future<bool> fundPaymentChannel(
    _i3.PaymentChannelDescriptor? descriptor,
    String? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fundPaymentChannel,
          [
            descriptor,
            amount,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
  @override
  _i6.Future<Map<String, String>> preparePayment({
    required String? destinationAddress,
    required String? authAmount,
    required _i3.PaymentChannelDescriptor? channelDescriptor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #preparePayment,
          [],
          {
            #destinationAddress: destinationAddress,
            #authAmount: authAmount,
            #channelDescriptor: channelDescriptor,
          },
        ),
        returnValue: _i6.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i6.Future<Map<String, String>>);
  @override
  String sendDrops(
    String? amount,
    String? channelId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendDrops,
          [
            amount,
            channelId,
          ],
        ),
        returnValue: '',
      ) as String);
  @override
  _i6.Future<dynamic> submitRequest(
    _i7.BaseRequest? request,
    _i7.Client? client,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitRequest,
          [
            request,
            client,
          ],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);
  @override
  _i6.Future<dynamic> getAvailableNFTs() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableNFTs,
          [],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);
  @override
  _i6.Future<bool> acceptOffer(String? offerIndex) => (super.noSuchMethod(
        Invocation.method(
          #acceptOffer,
          [offerIndex],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
  @override
  _i6.Future<List<_i3.NFTOffer>> getNFTOffers(String? nfTokenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNFTOffers,
          [nfTokenId],
        ),
        returnValue: _i6.Future<List<_i3.NFTOffer>>.value(<_i3.NFTOffer>[]),
      ) as _i6.Future<List<_i3.NFTOffer>>);
  @override
  _i6.Future<List<_i3.PaymentChannelDescriptor>> getOpenPaymentChannels(
          {String? destination_address}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOpenPaymentChannels,
          [],
          {#destination_address: destination_address},
        ),
        returnValue: _i6.Future<List<_i3.PaymentChannelDescriptor>>.value(
            <_i3.PaymentChannelDescriptor>[]),
      ) as _i6.Future<List<_i3.PaymentChannelDescriptor>>);
  @override
  _i6.Future<_i3.PaymentChannelDescriptor> openPaymentChannel(
    String? destinationAddress,
    String? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #openPaymentChannel,
          [
            destinationAddress,
            amount,
          ],
        ),
        returnValue: _i6.Future<_i3.PaymentChannelDescriptor>.value(
            _FakePaymentChannelDescriptor_1(
          this,
          Invocation.method(
            #openPaymentChannel,
            [
              destinationAddress,
              amount,
            ],
          ),
        )),
      ) as _i6.Future<_i3.PaymentChannelDescriptor>);
}

/// A class which mocks [XummWallet].
///
/// See the documentation for Mockito's code generation for more information.
class MockXummWallet extends _i1.Mock implements _i8.XummWallet {
  MockXummWallet() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get address => (super.noSuchMethod(
        Invocation.getter(#address),
        returnValue: '',
      ) as String);
  @override
  _i2.ValueNotifier<String?> get balance => (super.noSuchMethod(
        Invocation.getter(#balance),
        returnValue: _FakeValueNotifier_0<String?>(
          this,
          Invocation.getter(#balance),
        ),
      ) as _i2.ValueNotifier<String?>);
  @override
  String publicKey() => (super.noSuchMethod(
        Invocation.method(
          #publicKey,
          [],
        ),
        returnValue: '',
      ) as String);
  @override
  _i6.Future<bool> fundPaymentChannel(
    _i3.PaymentChannelDescriptor? descriptor,
    String? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fundPaymentChannel,
          [
            descriptor,
            amount,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
  @override
  _i6.Future<Map<String, String>> preparePayment({
    required String? destinationAddress,
    required String? authAmount,
    required _i3.PaymentChannelDescriptor? channelDescriptor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #preparePayment,
          [],
          {
            #destinationAddress: destinationAddress,
            #authAmount: authAmount,
            #channelDescriptor: channelDescriptor,
          },
        ),
        returnValue: _i6.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i6.Future<Map<String, String>>);
  @override
  _i6.Future<dynamic> submitRequest(
    _i7.BaseRequest? request,
    _i7.Client? client,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitRequest,
          [
            request,
            client,
          ],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);
  @override
  _i6.Future<dynamic> getAvailableNFTs() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableNFTs,
          [],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);
  @override
  _i6.Future<bool> acceptOffer(String? offerIndex) => (super.noSuchMethod(
        Invocation.method(
          #acceptOffer,
          [offerIndex],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
  @override
  _i6.Future<List<_i3.NFTOffer>> getNFTOffers(String? nfTokenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNFTOffers,
          [nfTokenId],
        ),
        returnValue: _i6.Future<List<_i3.NFTOffer>>.value(<_i3.NFTOffer>[]),
      ) as _i6.Future<List<_i3.NFTOffer>>);
  @override
  _i6.Future<_i3.PaymentChannelDescriptor> openPaymentChannel(
    String? destinationAddress,
    String? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #openPaymentChannel,
          [
            destinationAddress,
            amount,
          ],
        ),
        returnValue: _i6.Future<_i3.PaymentChannelDescriptor>.value(
            _FakePaymentChannelDescriptor_1(
          this,
          Invocation.method(
            #openPaymentChannel,
            [
              destinationAddress,
              amount,
            ],
          ),
        )),
      ) as _i6.Future<_i3.PaymentChannelDescriptor>);
  @override
  _i6.Future<List<_i3.PaymentChannelDescriptor>> getOpenPaymentChannels(
          {String? destination_address}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOpenPaymentChannels,
          [],
          {#destination_address: destination_address},
        ),
        returnValue: _i6.Future<List<_i3.PaymentChannelDescriptor>>.value(
            <_i3.PaymentChannelDescriptor>[]),
      ) as _i6.Future<List<_i3.PaymentChannelDescriptor>>);
  @override
  _i6.Future<_i4.Response> XummRequest(
    Map<String, dynamic>? tx_json,
    Map<String, dynamic>? options,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #XummRequest,
          [
            tx_json,
            options,
          ],
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #XummRequest,
            [
              tx_json,
              options,
            ],
          ),
        )),
      ) as _i6.Future<_i4.Response>);
}
