name: deployed-prod
'on':
  push:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Configure the app for staging
        run: |
          mv firebase{.staging,}.json
          mv lib/firebase_options{.staging,}.dart 
      - name: Build the app
        run: flutter build web --release  --release -t lib/main.xumm.dart
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KERNML }}'
          channelId: live
          projectId: kernml
